name: Deploy to Firebase Hosting

on:
  push:
    tags:
      - "v*"

permissions:
  checks: write
  contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - run: pnpm lint && pnpm build:web
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.GOOGLE_FIREBASE_SERVICE_ACCOUNT }}
          projectId: ${{ secrets.GOOGLE_FIREBASE_PROJECT_ID }}
